version: "3.8"
services:
  backend:
    image: backend
    container_name: backend
    build: 
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - 3300:3300

  frontend:
    image: frontend
    container_name: frontend
    build: 
      dockerfile: ./apps/frontend/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend