export enum UnauthorizedExceptionType {
    UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
    NO_AUTHORIZATION_TOKEN = 'NO_AUTHORIZATION_TOKEN',
    USER_NOT_REGISTERED = 'USER_NOT_REGISTERED',
    NO_USER_ROLE = 'USER_HAS_NO_ROLE',
    WRONG_PASSWORD = 'PASSWORD OR EMAIL IS INCORRECT'
}
export enum ForbiddenExceptionType {
    FORBIDDEN = 'FORBIDDEN',
    EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED'
}

export enum UserExceptionType {
    USER_ALREADY_EXIST = 'USER_ALREADY_EXIST',
    PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT'
}
export enum BadRequestExceptionType {
    BAD_REQUEST = 'BAD_REQUEST',
    MISSING_FILE_TYPE = 'MISSING_FILE_TYPE',
    MISSING_FILE = 'MISSING_FILE'
}
export enum CommentLikeExceptionType {
    COMMENT_ALREADY_LIKED = 'COMMENT_ALREADY_LIKED'
}
