// import 'tailwindcss/tailwind.css';
import { NextAuthProvider } from './Provider';
import Navbar from './components/Navbar';
import './tailwind.css';

export const metadata = {
    title: 'Welcome to frontend',
    description: 'Generated by create-nx-workspace'
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="flex flex-grow flex-col h-screen">
                <NextAuthProvider>
                    <Navbar />
                    {children}
                </NextAuthProvider>
            </body>
        </html>
    );
}
